### ISSUE TITLE
Feature Request: Support for volume mounts

### ISSUE THREAD

**Issue by goffinf** [GoogleCloudPlatform/container-structure-test#53]
I would like to support some tests that require a volume to be mounted for the Container Under Test.

I don't see an option for that in the current release ?

**Comment by nkubala** [comment]
This one is interesting because it gets into the difference between a structure test and an "integration" test. In order to mount a volume in a container you have to actually run it, which is sort of counter to what we want to support with this framework. However this is essentially what we're doing with setup commands (run them and then commit the resulting container), so I suppose in theory we could do the same thing to support volume mounting.

**Comment by micapam** [comment]
Is there a `container-integration-test` or plans for one, then?

**Comment by nkubala** [comment]
@micapam no current plans for a separate integration testing framework, but that's not to say we won't in the future! We're focusing more on expanding the use cases of the structure tests right now.

**Comment by nkubala** [comment]
This issue is superseded by https://github.com/GoogleCloudPlatform/container-structure-test/issues/70, so closing to track over there.
