### ISSUE TITLE
ExpectedError appears to only work without brackets

### ISSUE THREAD

**Issue by cognitiaclaeves** [GoogleCloudPlatform/container-structure-test#54]
```
- name: ensure nomad version
  command: '/usr/local/bin/nomad'
  args: ['--version']
  expectedError: 'Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)'
```

works:

> --- PASS: TestAll/Command_Test:_ensure_nomad_version (0.41s)
> 	docker_driver.go:88: stderr: Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)

```
- name: ensure nomad version
  command: '/usr/local/bin/nomad'
  args: ['--version']
  expectedError: ['Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)']
```

doesn't:

> --- FAIL: TestAll/Command_Test:_ensure_nomad_version (0.38s)
> 	docker_driver.go:88: stderr: Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)
> 	utils.go:33: Expected string 'Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)' not found in error!

**Comment by nkubala** [comment]
Hey @cognitiaclaeves, thanks for reporting. The strings provided to the expected/excluded output/error fields should actually be regexes, not raw strings. If you use the string `Nomad v0\.7\.1\+ent \(83ac1d7316a79aacb09d349298e14e23a0aa9853\)` (escaping special regex characters), your second example with the brackets will work.

This is unfortunately a bit of a misleading result, because the first test passed due to the fact that the field you provided to the `expectedError` was actually never parsed correctly. This made the test framework think you simply hadn't provided any fields to check, so everything seemed normal. This is just an unfortunate side effect of the way that YAML parsing works in golang.

**Comment by cognitiaclaeves** [comment]
This made more sense. Your solution works for me. Thanks!
