### ISSUE TITLE
tar option failing to pull image layer

### ISSUE THREAD

**Issue by oztigertim** [GoogleCloudPlatform/container-structure-test#71]
I have the container-structure-test working on xubuntu 16.04 64 bit for a couple of simple file existence tests for the default docker driver but I haven't been able to get the tar driver to pull the image.
I'm getting errors like:
ERRO[0110] Failed to pull image layer: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs...

I've tried on different machines and different locations.
Is there a trick to getting the tar option to work? 

My command line is:
sudo ./container-structure-test -test.v -driver tar -image python python_file_test.yaml

**Comment by oztigertim** [comment]
On the work computer I was using two different VirtualBox xubuntu images. I noticed at the end of the error it mentioned "i/o timeout". I thought perhaps VirtualBox on Win10 may be causing an issue so I've tried at home on my Xubuntu 16.04 laptop and its working but its really really slow.
Also it displays a lot of ERRO but the file exist test still passes.
$ sudo ./container-structure-test -driver tar -image python python_file_test.yaml 
Using driver tar
2018/02/28 16:48:11 Running tests for file python_file_test.yaml
Retrieving image python from source Cloud Registry
ERRO[0048] remove /tmp/python156232896/etc/dpkg/.wh.shlibs.default: no such file or directory 
ERRO[0048] remove /tmp/python156232896/etc/dpkg/.wh.shlibs.override: no such file or directory

**Comment by nkubala** [comment]
Hey @oztigertim, thanks for filing. Glad to hear you got something working, but sorry to hear it's so slow. 

I think I'm a bit confused on the image you're trying to run tests on; you're passing `-image python`, so is that supposed to be an image you built locally? Otherwise it should basically try and do `docker pull python`, which would normally work. I can't tell for sure but it looks like you have a private remote registry set up, based on the URL in the error you posted.

The errors you're seeing definitely shouldn't be there, so I'm looking into that. Looks like an issue with whiteout layers.

**Comment by oztigertim** [comment]
Hey @nkubala yes I'm expecting it to just do a docker pull. If I use the docker driver instead of the tar driver it works fine. I'm not using a private registry. 
On my home Xubuntu laptop the end of the output looks like this:
ERRO[0152] remove /tmp/python638756840/var/lib/dpkg/info/.wh.libtimedate-perl.md5sums: no such file or directory 
INFO[0162] Finished prepping image python               
--- FAIL: TestAll (162.11s)
    --- PASS: TestAll/File_Existence_Test:_Root (55.16s)
    --- FAIL: TestAll/File_Existence_Test:_python (53.54s)
    	structure.go:94: File /usr/local/bin/python should exist but does not, got error: stat /tmp/python905351533/usr/local/bin/python: no such file or directory!
    --- PASS: TestAll/Metadata_Test (53.40s)
	structure_test.go:49: Total tests run: 2
FAIL

If I was completing this test with dgoss I'd expect it to take less than a second.
Perhaps there could be an option to use a local container rather than trying to pull it for the tar driver?

**Comment by nkubala** [comment]
@oztigertim this should be fixed now. There were a few issues, mostly fixed in [container-diff](https://github.com/GoogleCloudPlatform/container-diff) but also one here.

One thing I want to note is that when using the tar driver, the framework will unpack the tarball representing the image filesystem on your machine before running any tests; this will always take longer than running the container in your local Docker daemon. If you have the image in a local daemon, you probably want to be using the `docker` driver instead of the `tar` driver.

While dgoss can be faster in some cases, it relies on being able to run Docker locally, which we consider a limitation since it won't run in environments where a Docker daemon isn't present. dgoss also starts a container and examines the running process to validate structure of the container; this is more of an "integration" style test, since running a container can completely alter the original structure of the image. container-structure-test only validates the unmodified container created from the base image.
